#include "constdata.h"

const scale_chord_t scaleModes[] = {
  { "Ionian (Major)", 7, {2, 2, 1, 2, 2, 2, 1} },
  { "Dorian",         7, {2, 1, 2, 2, 2, 1, 2} },
  { "Phygrian",       7, {1, 2, 2, 2, 1, 2, 2} },
  { "Lydian",         7, {2, 2, 2, 1, 2, 2, 1} },
  { "Mixolydian",     7, {2, 2, 1, 2, 2, 1, 2} },
  { "Aeolian (Minor)",7, {2, 1, 2, 2, 1, 2, 2} },
  { "Locrian",        7, {1, 2, 2, 1, 2, 2, 2} },
  { "Augmented",      6, {3, 1, 3, 1, 3, 1} },
  { "BeBop",          8, {2, 2, 1, 2, 2, 1, 1, 1} },
  { "Blues",          6, {3, 2, 1, 1, 3, 2} },
  { "Chromatic",      12, {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1} },
  { "Double Harmonic",7, {1, 3, 1, 2, 1, 3, 1} },
  { "Enigmatic",      7, {1, 3, 2, 2, 2, 1, 1} },
  { "Flamenco",       7, {1, 3, 1, 2, 1, 3, 1} },
  { "Half Dimnished", 7, {2, 1, 2, 1, 2, 2, 2} },
  { "Harmonic Maj",   7, {2, 2, 1, 2, 1, 3, 1} },
  { "Harmonic Min",   7, {2, 1, 2, 2, 1, 3, 1} },
  { "Hirajoshi",      5, {4, 2, 1, 4, 1} },
  { "Hungarian Gyp",  7, {2, 1, 3, 1, 1, 3, 1} },
  { "Hungarian Maj",  7, {3, 1, 2, 1, 2, 1, 2} },
  { "Insen",          5, {1, 4, 2, 4, 2} },
  { "Istrian",        4, {1, 2, 1, 2} },
  { "Iwato",          5, {1, 4, 1, 4, 2} },
  { "Lydian (Aug)",   7, {2, 2, 2, 2, 1, 2, 1} },
  { "Major BeBop",    8, {2, 2, 1, 2, 1, 1, 2, 1} },
  { "Major Locrian",  7, {2, 2, 1, 1, 2, 2, 2} },
  { "Major Pent",     5, {2, 2, 3, 2, 3} },
  { "Melodic Min Asc",7, {2, 1, 2, 2, 2, 2, 1} },
  { "Melodic Min Des",7, {2, 2, 1, 2, 2, 1, 2} },
  { "Minor Pent",     5, {3, 2, 2, 3, 2} },
  { "Neapolitan Maj", 7, {1, 2, 2, 2, 2, 2, 1} },
  { "Neapolitan Min", 7, {1, 2, 2, 2, 1, 3, 1} },
  { "Octanoic",       8, {2, 1, 2, 1, 2, 1, 2, 1} },
  { "Persian",        7, {1, 3, 1, 1, 2, 3, 1} },
  { "Phygrian Dom",   7, {1, 3, 1, 2, 1, 2, 2} },
  { "Prometheus",     6, {2, 2, 2, 3, 1, 2} },
  { "Harmonics",      6, {3, 1, 1, 2, 2, 3} },
  { "Tritone",        6, {1, 2, 3, 1, 3, 2} },
  { "2semi Tritone",  5, {1, 1, 4, 1, 1} },
  { "Ukranian",       7, {2, 1, 3, 1, 2, 1, 2} },
  { "Whole Tone",     6, {2, 2, 2, 2, 2, 2} },
  { "Yo",             5, {3, 2, 2, 3, 2} }
};

const scale_chord_t chordPatterns[] = {
  { "Major Triad", 2, {4, 7}},
  { "Major 6th",   3, {4, 7, 9}},
  { "Dom 7th",     3, {4, 7, 10}},
  { "Major 7th",   3, {4, 7, 11}},
  { "Aug Triad",   2, {4, 8}},
  { "Aug 7th",     3, {4, 8, 10}},
  { "Minor Triad", 2, {3, 7}},
  { "Minor 6th",   3, {3, 7, 9}},
  { "Minor 7th",   3, {3, 7, 10}},
  { "Min-Maj 7th", 3, {3, 7, 11}},
  { "Dim Triad",   2, {3, 6}},
  { "Dim 7th",     3, {3, 6, 9}},
  { "Half  Dim 7th",3,{3, 6, 10}}
};

// keys from 48 up - black (1) or white (0)
const keyb_t keybd[] = {
  { 0, 0 },
  { 1, KEY_WIDTH * 0.5 },
  { 0, KEY_WIDTH },
  { 1, KEY_WIDTH * 1.5 },
  { 0, KEY_WIDTH * 2 },
  { 0, KEY_WIDTH * 3 },
  { 1, KEY_WIDTH * 3.5 },
  { 0, KEY_WIDTH * 4 },
  { 1, KEY_WIDTH * 4.5 },
  { 0, KEY_WIDTH * 5 },
  { 1, KEY_WIDTH * 5.5 },
  { 0, KEY_WIDTH * 6 },
  { 0, KEY_WIDTH * 7 },
  { 1, KEY_WIDTH * 7.5 },
  { 0, KEY_WIDTH * 8 },
  { 1, KEY_WIDTH * 8.5 },
  { 0, KEY_WIDTH * 9 },
  { 0, KEY_WIDTH * 10 },
  { 1, KEY_WIDTH * 10.5 },
  { 0, KEY_WIDTH * 11 },
  { 1, KEY_WIDTH * 11.5 },
  { 0, KEY_WIDTH * 12 },
  { 1, KEY_WIDTH * 12.5 },
  { 0, KEY_WIDTH * 13 },
  { 0, KEY_WIDTH * 14 },
  { 1, KEY_WIDTH * 14.5 },
  { 0, KEY_WIDTH * 15 },
  { 1, KEY_WIDTH * 15.5 },
  { 0, KEY_WIDTH * 16 },
  { 0, KEY_WIDTH * 17 },
  { 1, KEY_WIDTH * 17.5 },
  { 0, KEY_WIDTH * 18 },
  { 1, KEY_WIDTH * 18.5 },
  { 0, KEY_WIDTH * 19 },
  { 1, KEY_WIDTH * 19.5 },
  { 0, KEY_WIDTH * 20 }
};

const char * waves[] = {
  "Sine",
  "Saw",
  "Square",
  "Triangle",
  "Arbitrary",
  "Pulse",
  "Rev Saw",
  "S/H"
};

const char * bands[] = {
  "Off",
  "LPF",
  "BPF",
  "HPF"
};

const char * arpModes[] = {
  "Off",
  "Up",
  "Down",
  "Up/Down",
  "Random"
};

const char * instrumentNames[] = {
  "Piano1",
  "Piano2",
  "Piano3",
  "Honkytonk",
  "EPiano1",
  "EPiano2",
  "Harpsichord",
  "Clav",
  "Celesta",
  "Glockenspiel",
  "MusicBox",
  "Vibraphone",
  "Marimba",
  "Xylophone",
  "Tubularbell",
  "Santur",
  "Organ1",
  "Organ2",
  "Organ3",
  "ChurchOrg1",
  "ReedOrgan",
  "AccordionFr",
  "Harmonica",
  "Bandoneon",
  "NylonstrGt",
  "SteelstrGt",
  "JazzGt",
  "CleanGt",
  "MutedGt",
  "OverdriveGt",
  "DistortionGt",
  "GtHarmonics",
  "AcousticBs",
  "FingeredBs",
  "PickedBs",
  "FretlessBs",
  "SlapBass1",
  "SlapBass2",
  "SynthBass1",
  "SynthBass2",
  "Violin",
  "Viola",
  "Cello",
  "Contrabass",
  "TremoloStr",
  "PizzicatoStr",
  "Harp",
  "(missing) timpani",
  "Strings",
  "SlowStrings",
  "SynStrings1",
  "SynStrings2",
  "ChoirAahs",
  "VoiceOohs",
  "SynVox",
  "OrchestraHit",
  "Trumpet",
  "Trombone",
  "Tuba",
  "MutedTrumpet",
  "FrenchHorns",
  "Brass1",
  "SynthBrass1",
  "SynthBrass2",
  "SopranoSax",
  "AltoSax",
  "TenorSax",
  "BaritoneSax",
  "Oboe",
  "EnglishHorn",
  "Bassoon",
  "Clarinet",
  "Piccolo",
  "Flute",
  "Recorder",
  "PanFlute",
  "BottleBlow",
  "Shakuhachi",
  "Whistle",
  "Ocarina",
  "SquareWave",
  "SawWave",
  "SynCalliope",
  "ChifferLead",
  "Charang",
  "SoloVox",
  "FifthSawWave",
  "BassLead",
  "Fantasia",
  "WarmPad",
  "Polysynth",
  "SpaceVoice",
  "BowedGlass",
  "MetalPad",
  "HaloPad",
  "SweepPad",
  "IceRain",
  "Soundtrack",
  "Crystal",
  "Atmosphere",
  "Brightness",
  "Goblin",
  "EchoDrops",
  "StarTheme",
  "Sitar",
  "Banjo",
  "Shamisen",
  "Koto",
  "Kalimba",
  "Bagpipe",
  "Fiddle",
  "Shanai",
  "TinkleBell",
  "Agogo",
  "SteelDrums",
  "(missing) woodblock",
  "Taiko",
  "MeloTom1",
  "SynthDrum",
  "ReverseCym",
  "(missing) fret noise",
  "BreathNoise",
  "Seashore",
  "Bird",
  "Telephone1",
  "Helicopter",
  "Applause",
  "(missing) gun shot"
};

const char * noteNames[] = {
  "C",
  "C# / Db",
  "D",
  "D# / Eb",
  "E",
  "F",
  "F# / Gb",
  "G",
  "G# / Ab",
  "A",
  "A# / Bb",
  "B"
};
